name: Build and upload artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-package:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies & Build artifacts
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller==6.17.0
          cd src
          python build_package.py

      # 可选：如果需要自动生成 tag/changelog 的 action，确保把 token 放 env（不要放在 with）
      # - name: Auto Tag (optional)
      #   uses: Klemensas/action-autotag@stable
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     version: "patch"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flaresolverr-${{ matrix.os }}
          path: |
            ./dist
            ./src/dist
          retention-days: 7